### ISSUE TITLE
About referencing

### ISSUE THREAD

**Issue by carlo1998** [dwp-forge/refnotes#29]
Hello guys! Thanks for the plugin, it's so wonderful!
What I want for my DokuWiki site is to have a single page containing **all** the references that I use in my wiki. I think it can be done with **Reference Databases**, so I tried what was mentioned there, but they don't work (or it's just that there is something wrong with what I'm doing)!  I also looked on other related pages of **Refnotes**, but I still can't find what I want there. Can you tell me what can I do about this?
Thanks again!~~~

**Comment by dwp-forge** [comment]
What exactly did you try? How do you define the notes in the database? How do you use them? Where the database is located? What's in the settings?

Also, which versions of DokuWiki and RefNotes do you use?
