### ISSUE TITLE
change id after edit

### ISSUE THREAD

**Issue by adrianevs** [dwp-forge/refnotes#32]
Hy, i found a serious problem.

I give you an example to be easy to understand

If i have text of 20 rows.
I pus a ref at row 11 and save the page, that's ref will have id 1. and i will put the same ref to row 16 and 17 using syntax [(#1)].
If someone will edit the page after a time and will ad a ref at row 2, this ref will have now id1 and the ref of row 11 will have id 2, and here is the pronlem, because after that this ref  from row 2 will appear on row 16 and 17, and that's wrong.

**Comment by dwp-forge** [comment]
Please read the [documentation](https://www.dokuwiki.org/plugin:refnotes:syntax#named_notes):

> Referring to a note by it's number is error-prone as over the history of the page this number can change. Alternative way of the note identification is giving it a unique name.
