### ISSUE TITLE
Refnote missing from config interface

### ISSUE THREAD

**Issue by gyula21** [dwp-forge/refnotes#33]
Refnote missing from plugin config interface
![refnotes](https://cloud.githubusercontent.com/assets/3487559/14790414/7f90d8e0-0b11-11e6-9fcc-eb7baad91823.PNG)

**Comment by dwp-forge** [comment]
Please provide more information. Which DokuWiki version? Which PHP version? Which Refnotes version? Was it working before or did you install Refnotes first time? Did you try it on a fresh DokuWiki installation without all other plugins?

The more details you provide the easier it will be to figure out the root cause.

**Comment by gyula21** [comment]
I use the newest dokuwikionstick version.
PHP is the "mini php server" what is provided to the dokuwikionstick
I installed the newest refnotes.
It's working but doesn't appear in the config interfac (I want to configure a ref-db)

I didn't tried it yet

**Comment by dwp-forge** [comment]
Just tried fresh DokuWikiStick install -- plugin shows up on the configuration page as expected.

![detritus](https://cloud.githubusercontent.com/assets/11460562/14831913/52db3e40-0c00-11e6-96f9-9f4f1db3d40a.png)

Could be conflict with another plugin. Could you check?

**Comment by gyula21** [comment]
I deleted some old plugins, what I didn't used, and now it appeared :)

**Comment by dwp-forge** [comment]
Okay, let's say that it's fixed for now. Still would be nice to know with which plugins RefNotes conflicts, though.

**Comment by gyula21** [comment]
I deleted the templater plugin, the discussions plugin, the captcha plugin, the notes plugin and the indexmenu plugin

**Comment by dwp-forge** [comment]
Just installed:
- http://www.dokuwiki.org/plugin:templater
- http://www.dokuwiki.org/plugin:discussion
- http://www.dokuwiki.org/plugin:captcha
- http://www.dokuwiki.org/plugin:note
- http://www.dokuwiki.org/plugin:indexmenu

RefNotes still shows up in the admin UI.

**Comment by gyula21** [comment]
I don't know what was wrong, but for me after I deleted these plugins it appeared :)
