### ISSUE TITLE
using - in cite keys

### ISSUE THREAD

**Issue by Jas2Ma** [dwp-forge/refnotes#34]
I'm using better bibtex pluging for zotero which uses "-" characters in cite keys. I actually found no documentation for bibtex cite keys, but "-" seems to agree with my bibtex.

Nevertheless refnotes does not like "-", I can't get a refnotes reference using "-" characters in cite keys. Can you fix this?

**Comment by dwp-forge** [comment]
The BibTeX support was added as an extension of [named note syntax](https://www.dokuwiki.org/plugin:refnotes:syntax#named_notes). The names use DW page naming convention (alphanumerics plus "_"), so "-" was not supposed to be supported. Yet BibTeX example uses ":ref:Knuth-LCE-1985" as a name. Not sure anymore if it was planned or I just overlooked and didn't test properly. In any case it's a bug either in the code or in the documentation.

I no longer actively work on the plugin, and it would take me some time to figure side effects of such a change. There are number of ways to define and use a note and all of them should be considered before extending the syntax. The easiest way would be just to update the documentation to ":ref:Knuth_LCE_1985" but I guess that is not the solution you are looking for.

Maybe if I will have a spare weekend and I'll look into this in more detail but I cannot promise anything. The pull requests are welcome, though.

**Comment by Jas2Ma** [comment]
Too bad you don't actively work on this plugin anymore. Since this problem is giving me real trouble, I may at least find some workaround for me. Don't know whether I will take the time to search for a profound solution, because I have no qualification regarding this problem at the moment.

**Comment by dwp-forge** [comment]
I looked at the code again and it turned out that "-" is supported throughout the plugin. It was just BibTeX parser that could not handle it. I already [released the fix](https://www.dokuwiki.org/plugin:refnotes#section20160812).

**Comment by Jas2Ma** [comment]
Perfect! Thanks a lot!
