### ISSUE TITLE
Store RefNote configuration in the /conf directory

### ISSUE THREAD

**Issue by kyllingstad** [dwp-forge/refnotes#41]
I think it would be preferable if RefNotes stored its configuration in the `/conf` directory, together with DokuWiki's, as this would ease backup and migration.

The DW documentation lists `/conf` as [one of the directories which should be backed up](https://www.dokuwiki.org/faq:backup), while `/lib/plugins` is not among the directories on that list. Furthermore, the DW installation guide only specifies that the `/lib/plugins` directory ["must be writable by the web process for the Extension Manager to work"](https://www.dokuwiki.org/install:permissions). It says nothing about it being required for the plugins themselves to work. These things make me suspect that storing configuration in the plugin directory is somewhat unconventional.

In my setup, the `/conf` and `/data` directories are actually the only ones that are writable by the web server process, which to me seems like a sensible setup in terms of security and maintainability.

**Comment by dwp-forge** [comment]
Good idea.

**Comment by kyllingstad** [comment]
Actually, it seems it is recommended that plugins use [DokuWiki's built-in configuration mechanism](https://www.dokuwiki.org/devel:configuration). Then, any configuration changes automatically get stored in `/conf/local.php`.

**Comment by dwp-forge** [comment]
That's true, but I find that mechanism quite limiting for RefNotes heeds. Every setting there stores a single value, which will work great for things like reference database namespace. But by the time you get to namespace configuration that concept starts to break. Maybe with some trickery you could bend the built-in settings to store multi-value parameters, but I don't think that's worth the effort.

**Comment by dwp-forge** [comment]
Released in [v.2017-02-28](https://github.com/dwp-forge/refnotes/releases/tag/v.2017-02-28).
