### ISSUE TITLE
Refnotes not compatible with the latest version of dokuwiki (2018-04-22 "Greebo")

### ISSUE THREAD

**Issue by kvnyang** [dwp-forge/refnotes#44]
**Refnotes** plugin is not compatible with the latest version of dokuwiki (**2018-04-22 "Greebo"**).

Both the wiki pages with **Refnotes** syntax and the **RefNotes** Configuration page show the following error information:

`Fatal error: Uncaught Error: Cannot access protected property action_plugin_refnotes::$lang in /var/www/html/lib/plugins/refnotes/locale.php:72 Stack trace: #0 /var/www/html/lib/plugins/refnotes/database.php(73): refnotes_localization->getByPrefix('dbk') #1 /var/www/html/lib/plugins/refnotes/database.php(51): refnotes_reference_database->loadKeys() #2 /var/www/html/lib/plugins/refnotes/database.php(29): refnotes_reference_database->load() #3 /var/www/html/lib/plugins/refnotes/note.php(277): refnotes_reference_database::getInstance() #4 /var/www/html/lib/plugins/refnotes/note.php(267): refnotes_action_note->loadDatabaseDefinition() #5 /var/www/html/lib/plugins/refnotes/core.php(481): refnotes_action_note->__construct(Object(refnotes_scope), ':ref:as:is:tex:', 'wp_tex') #6 /var/www/html/lib/plugins/refnotes/core.php(301): refnotes_action_core->createNote(Object(refnotes_scope), ':ref:as:is:tex:', 'wp_tex') #7 /var/www/html/lib/plugins/refnotes/core.php(450): refnotes_core->getNote(':ref:as:is:tex:', 'wp_tex') #8 /var/www/ht in /var/www/html/lib/plugins/refnotes/locale.php on line 72
`

**Comment by LarsGit223** [comment]
Fixed by commit dec23e5d0f6a7e7746271e7f0df9389c651ea171.

**Comment by dwp-forge** [comment]
Fixed in release [2018-05-01](https://github.com/dwp-forge/refnotes/releases/tag/v.2018-05-01).
