### ISSUE TITLE
Can't start a phrase with direct author citation

### ISSUE THREAD

**Issue by coldscientist** [dwp-forge/refnotes#47]
Consider the following reference:

[(:harvard:Empreendedorismo-Hashimoto>>
title: Espírito empreendedor nas organizações: aumentando a competitividade através do intraempreendedorismo
author: Marcos Hashimoto
ref-author: Hashimoto
publisher: Saraiva
year: 2013
)]

For e.g, the following phare WON'T generate the mark up correctly:

[(:harvard:Empreendedorismo-Hashimoto>>direct:yes)] trouxe para o estudo da administração uma abrangência maior...

OUTPUT:

 trouxe para o estudo da administração uma abrangência maior...

But the following generates the markup correctly:

A nova abordagem de Ducker, segundo [(:harvard:Empreendedorismo-Hashimoto>>direct:yes)], trouxe para o estudo da administração uma abrangência maior...

OUTPUT:

A nova abordagem de Ducker, segundo Hashimoto (2006), trouxe para o estudo da administração uma abrangência maior...

Notes that in the first output, Hashimoto is not printed. But it's printed normally if the direct isn't in the start of the phrase.

Not a big issue, but every time I need to write the phrases in a way that direct citations isn't the first word in the phrase.

**Comment by dwp-forge** [comment]
Actually, that's not a bug but a [feature](https://www.dokuwiki.org/plugin:refnotes:syntax#hidden_references). I'll try to limit hiding only to paragraphs with no other text.

**Comment by dwp-forge** [comment]
Implemented in release [2019-02-09](https://www.dokuwiki.org/plugin:refnotes#section20190209).
