### ISSUE TITLE
author-ref not used in Bibtex

### ISSUE THREAD

**Issue by coldscientist** [dwp-forge/refnotes#48]
The following BibTex example:

```
@Book{:harvard:GangOfFour,
  author     = "Erich {Gamma} and Richard {Helm} and Ralph {Johnson} and John {Vlissides}",
  author-ref = "Gamma, et al.",
  title      = "Design Patterns: Elements of Reusable Object-Oriented Software",
  publisher  = "Addison-Wesley",
  year       = 1994,
  address    = "Reading, Mass.",
  pages      = 395,
  isbn       = "0-201-63361-2",
  url        = "http://en.wikipedia.org/wiki/Design_Patterns"
}
```

This reference is available as built-in in ref-notes plug-in, so in theory it should work. Tried with author-ref, authors-ref and ref-authors too, but no avail.

In the following input:

`Test of [(:harvard:GangOfFour>>direct:yes)]`

Should output:

Test of Gamma, et al.

But it outputs:

Test of Erich Gamma, Richard Helm, Ralph Johnson, John Vlissides (1994)

**Comment by dwp-forge** [comment]
There were two bugs here:
1. The documentation incorrectly mentions `author-ref` instead of `ref-author`;
2. Handling of hyphens in BibTeX keys was missing.

Both issues are fixed in release [2019-02-09](https://www.dokuwiki.org/plugin:refnotes#section20190209).
