### ISSUE TITLE
Refnotes with Frustrick Manners

### ISSUE THREAD

**Issue by MartinRushton** [dwp-forge/refnotes#51]
Installing refnotes into a Frustrick Manners system results in all pages failing to display.  A legacy issue that probably doesn't need fixing but needs flagging up on the documentation page.

**Comment by dwp-forge** [comment]
On my local Frustrick Manners instance with latest RefNotes release basic functionality seems to be operational. Sometimes caching could be a problem, so you could try to wipe your DW cache directory.

If you are okay with using older DW version, you could as well try an older RefNotes version.

**Comment by MartinRushton** [comment]
Thanks, a couple of good ideas.  Otherwise I'll just leave it until I go to CentOS 8 and with the upgraded PHP can install Greebo.

**Comment by MartinRushton** [comment]
Clearing the cache didn't work, but the old version 2017-02-28 works fine.
