### ISSUE TITLE
Integration with Pandoc

### ISSUE THREAD

**Issue by l4nn1312** [dwp-forge/refnotes#53]
Howdy! I'm trying to type up my blog posts in emacs's org-mode and use pandoc to convert it to something this plugin can understand. Pandoc has support for DokuWiki no problem, but it's not getting the links right.

**Comment by dwp-forge** [comment]
I never tried Pandoc, so I would have to speculate here, but I would bet that it supports only basic DW syntax. This plugin uses custom syntax, so you I guess you would need to extend DW plugin in Pandoc or write a new one. That has little to do with this project. You should rather contact Pandoc developers.
