### ISSUE TITLE
White screen after update in Greebo

### ISSUE THREAD

**Issue by Juergen-aus-Koeln** [dwp-forge/refnotes#54]
Hi,

after updating the refnotes plugin to version 2020-08-10 the wiki page doesn't load any more. In my test wiki with Hogfather everything is fine, but under the old release Greebo there's obviously a bug in there.

Best regards
Juergen

**Comment by dwp-forge** [comment]
Fixes for compatibility with Hogfather are not backward compatible. Use [previous version](https://github.com/dwp-forge/refnotes/releases/tag/v.2019-02-09) of the plugin on Greebo.

**Comment by TStein1984** [comment]
Thank you very much. The solution to go back to the previous version helped me.
