### ISSUE TITLE
config page unusable

### ISSUE THREAD

**Issue by remygithub** [dwp-forge/refnotes#59]
### Description
- All fields in `General Settings` and `Namespaces` sections are disabled
  - Cannot enable reference database
- Fields in `Notes` section appear to be enabled but **no action** when trying to add a test note
- `Save` button is enabled but seems **no action**

### Attempted use
- Created a `:refnotes:` namespace in `root` 
  - Created a sub namespace and a page in it
  - Added a `Bibtex` code section with one reference
  - Added  `@Comment` for namespace per instructions
- Created a page in another namespace 
  - added reference to bibtex note => does not work (as expected since database is disabled)
  - added regular inline footnotes => works 

### Desired behaviour
- Would like to have a number of common lists of  `bibtex` notes to reference throughout the dokuwiki site
- In the referencing page would like ot have a journal-article-like section of numbered references
- Would prefer reference numbering like in a bibliography not footnotes: refering to the same note does not increase the reference index -- current behaviour  

### Site configuration
Using Firefox 78.0 with nginx.

Other plugins enabled:
```
find -maxdepth 1 -type d
./extension
./usermanager
./wrap
./acl
./info
./upgrade
./styling
./color
./todo
./nspages
./revert
./safefnrecode
./searchindex
./imagebox
./authplain
./note
./config
./indexmenu
./move
./filelist
./tag
./simplenavi
./pagenav
./catlist
./pagelist
./bureaucracy
./sqlite
./struct
./mathpublish
./highlightparent
./edittable
./refnotes
```

### Debugger Feedback
Debugger console output when loading `Refnotes` config page

**Error:**
```
Uncaught TypeError: fields.getItem(...).update is not a function
    updateFields http://127.0.1.1:XXXX/lib/plugins/refnotes/admin.js:710
    initialize http://127.0.1.1:XXXX/lib/plugins/refnotes/admin.js:632
    initialize http://127.0.1.1:XXXX/lib/plugins/refnotes/admin.js:1013
    <anonymous> http://127.0.1.1:XXXX/lib/plugins/refnotes/admin.js:1091
    jQuery 2
        e
        t
```

**Warning:**
```
jQuery.Deferred exception: fields.getItem(...).update is not a function updateFields@http://127.0.1.1:XXXX/lib/plugins/refnotes/admin.js:710:38
initialize@http://127.0.1.1:XXXX/lib/plugins/refnotes/admin.js:632:13
initialize@http://127.0.1.1:XXXX/lib/plugins/refnotes/admin.js:1013:20
@http://127.0.1.1:XXXX/lib/plugins/refnotes/admin.js:1091:24
e@http://127.0.1.1:XXXX/lib/exe/jquery.php?tseed=34a552433bc33cc9c3bc32527289a0b2:2:30005
l/</t<@http://127.0.1.1:XXXX/lib/exe/jquery.php?tseed=34a552433bc33cc9c3bc32527289a0b2:2:30307
 undefined
```

**Comment by remygithub** [comment]
You were right about interference but it was the [sprintdoc](https://www.dokuwiki.org/template:sprintdoc) template causing the problem:
```
$grep -Ril shuffle lib
  lib/tpl/sprintdoc/js/base/spc.js
  lib/scripts/jquery/jquery-ui-theme/smoothness.css
```

In `lib/tpl/sprintdoc/js/base/spc.js`:
```
    200 // + + + + + + + + + + + + + + + + + + + + + + + + + + + +
    201 // shuffle func for random values
    202 // + + + + + + + + + + + + + + + + + + + + + + + + + + + +
    203 Array.prototype.shuffle = function(){
    204     var tmp, rand;
    205     for(var i =0; i < this.length; i++){
    206         rand = Math.floor(Math.random() * this.length);
    207         tmp = this[i];
    208         this[i] = this[rand];
    209         this[rand] =tmp;
    210     }
    211 };
```

After disabling the [sprintdoc](https://www.dokuwiki.org/template:sprintdoc) template Refnotes config worked as expected!  Too bad about sprintdoc as I really liked it...

Thank you for your guidance on solving the issue!
Remy

PS: what is the preferred way to get help in configuring Refnotes?

**Comment by dwp-forge** [comment]
If you really like that template, you can try a workaround suggested in the SO page I linked above:

``` javascript
Object.defineProperty(Array.prototype, 'shuffle', {
    var tmp, rand;
    for(var i =0; i < this.length; i++){
        rand = Math.floor(Math.random() * this.length);
        tmp = this[i];
        this[i] = this[rand];
        this[rand] =tmp;
    }
});

As for the configuration, you could give an example of formatting you look for. Just create some dummy DW page using whatever formatting you need. I will see how close RefNotes can get to that.
```

**Comment by dwp-forge** [comment]
Apparently, since 2009 when admin page was created there was some progress in JS. In ECMAScript 6 (released in June 2015) they got a [proper `Map` object](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map), so here is no need to cook-up your own implementation anymore. Also the page from which I copied `HashMap` updated quite a bit and doesn't use `Array` as a base container anymore. I guess, it's time to update that part in RefNotes as well.

**Comment by remygithub** [comment]
I tried the re-write of `shuffle` you suggested and `sprintdoc` does not seem to play nice.  

`admin.js` bugs out way before reaching line 710 like before and I get the following errors:
```
Uncaught ReferenceError: DOKU_BASE is not defined
    sendRequest http://127.0.1.1:XXXX/lib/plugins/refnotes/admin.js:196
    loadSettings http://127.0.1.1:XXXX/lib/plugins/refnotes/admin.js:224
    initialize http://127.0.1.1:XXXX/lib/plugins/refnotes/admin.js:1024
    <anonymous> http://127.0.1.1:XXXX/lib/plugins/refnotes/admin.js:1091
```

Line 196 in `admin.js`:
`url     : DOKU_BASE + 'lib/exe/ajax.php',`

There are also weird and changing syntax errors in `js.php`:
-  Line 5357: `Uncaught SyntaxError: expected expression, got '='`
- Line 5573: `Uncaught SyntaxError: missing : after property id`

That `js.php` script has only 490 lines but it seems to source a bunch of other scripts. The weird parts are that the template related script seems to have only comments and that the error is changing when changing settings on the DW config page.

Anyway, all of the above seem related to [sprintdoc](https://www.dokuwiki.org/template:sprintdoc) and `RefNote` works when that template is not used.

Let me know if you want me to test anything when you decide to update `admin.js`

**Comment by remygithub** [comment]
As far as configuring Refnotes, I just want to have a Bibliography/References section that combines footnotes and citations in a format like IEEE, for example.

Here is an example for referring page:
```
====== Testing References ======
Testing footnote1[(Footnote_1)] and footnote2[(Footnote_2)]

Citing reference1 [(qpm_tomography:park_diffraction_2006)] and reference2 [(qpm_tomography:pan_computational_1983)].

Again citing reference1 [(qpm_tomography:park_diffraction_2006)] and reference2 [(qpm_tomography:pan_computational_1983)].

===== References =====
[(Footnote_1>FIrst footnote)]
[(Footnote_2>Second footnote)]
```

Bibliography page in `:refnotes:` namespace (sorry, I copied an existing page):
```
====== Initial Work On QPM Tomography ======
<refnotes qpm_tomography> inherit: :cite: </refnotes>

<code bibtex>
@Comment{refnotes,
  namespace = "qpm_tomography"
}

@article{park_diffraction_2006,
	title = {Diffraction phase and fluorescence microscopy},
	volume = {14},
	url = {http://www.opticsexpress.org/abstract.cfm?URI=oe-14-18-8263},
	doi = {10.1364/OE.14.008263},
	number = {18},
	urldate = {2014-04-08},
	journal = {Optics Express},
	author = {Park, YongKeun and Popescu, Gabriel and Badizadegan, Kamran and Dasari, Ramachandra R. and Feld, Michael S.},
	month = sep,
	year = {2006},
	keywords = {Fluorescence microscopy, Microscopy},
	pages = {8263--8268},
	file = {oe-14-18-8263.pdf:/home/remy/Zotero/storage/B4KZFRSC/oe-14-18-8263.pdf:application/pdf;Opt. Express Snapshot:/home/remy/Zotero/storage/4EFR4AG9/abstract.html:text/html;Opt. Express Full Text PDF:/home/remy/Zotero/storage/ENH4TXIA/Park et al. - 2006 - Diffraction phase and fluorescence microscopy.pdf:application/pdf}
}

@article{pan_computational_1983,
	title = {A computational study of reconstruction algorithms for diffraction tomography: {Interpolation} versus filtered-backpropagation},
	volume = {31},
	issn = {0096-3518},
	shorttitle = {A computational study of reconstruction algorithms for diffraction tomography},
	doi = {10.1109/TASSP.1983.1164196},
	abstract = {From the standpoint of reporting a new contribution, this paper shows that by using bilinear interpolation followed by direct two-dimensional Fourier inversion, one can obtain reconstructions of quality which is comparable to that produced by the filtered-backpropagation algorithm proposed recently by Devaney. For an N × N image reconstructed from N diffracted projections, the former approach requires approximately 4N FFT's, whereas the backpropagation technique requires approximately N2FFT's. We have also taken this opportunity to present the reader with a tutorial introduction to diffraction tomography, an area that is becoming increasingly important not only in medical imaging, but also in underwater and seismic mapping with microwaves and sound. The main feature of the tutorial part is the statement of the Fourier diffraction projection theorem, which is an extension of the traditional Fourier slice theorem to the case of image formation with diffracting illumination.},
	number = {5},
	journal = {IEEE Transactions on Acoustics, Speech and Signal Processing},
	author = {Pan, S. X. and Kak, A.C.},
	year = {1983},
	keywords = {Image reconstruction, Interpolation, Tomography, Acoustic diffraction, Biomedical imaging, Reconstruction algorithms, Lighting, Backpropagation algorithms},
	pages = {1262--1275}
}
</code>
```

I get:
![DW_Refnotes_Debug_Fig1](https://user-images.githubusercontent.com/19198545/90990549-7a596c00-e570-11ea-8bc5-73a08f423e33.png)

instead of the citations section to have
>[1] Y. Park, G. Popescu, K. Badizadegan, R. R. Dasari, and M. S. Feld, “Diffraction phase and fluorescence microscopy,” Opt. Express, vol. 14, no. 18, pp. 8263–8268, Sep. 2006,

>[2] S. X. Pan and A. C. Kak, “A computational study of reconstruction algorithms for diffraction tomography: Interpolation versus filtered-backpropagation,” IEEE Transactions on Acoustics, Speech and Signal Processing, vol. 31, no. 5, pp. 1262–1275, 1983.

Also 
- mutiple references to one citation or footnote should not increase the reference counter
- back links are not typically used for citations.  
- I would prefer that both footnotes and references to follow the same format and continue the numbered list ([1],..[4])

Anyway the current output is not what I am used to and I find it to clutter the page.  That said, it is not the end of the world.

Thanks again for helping me figure this thing out!

**Comment by dwp-forge** [comment]
Sorry, my bad. I missed one more layer of wrapping in that example. It should be:

``` javascript
Object.defineProperty(Array.prototype, 'shuffle', {
    value: function() {
        var tmp, rand;
        for(var i =0; i < this.length; i++){
            rand = Math.floor(Math.random() * this.length);
            tmp = this[i];
            this[i] = this[rand];
            this[rand] =tmp;
        }
    }
});
```

To get formatting closer to what you want try to inherit `harvard` styling for `qpm_tomography` namespace:

```
...
===== References =====
[(Footnote_1>FIrst footnote)]
[(Footnote_2>Second footnote)]

<refnotes></refnotes>

<refnotes qpm_tomography>
inherit: harvard
</refnotes>
```

The result:

![image](https://user-images.githubusercontent.com/11460562/91021255-357b1700-e5fc-11ea-8ddd-a91e91c38a10.png)

**Comment by remygithub** [comment]
The `Object.defineProperty` change to `lib/tpl/sprintdoc/js/base/spc.js` worked: now I can use sprintdoc with refnotes!

The changes to `Testing References` worked out to what I wanted as well after some tuning of `:harvard:`.

Thank you again! Let me know if there is any way I can pay back you kindness in helping with this.

**Comment by dwp-forge** [comment]
You are welcome :)

**Comment by dwp-forge** [comment]
Migrated to ES6 Map in 20b44e6.
