### ISSUE TITLE
bibtex.php issue

### ISSUE THREAD

**Issue by VadoLigure** [dwp-forge/refnotes#60]
Dokuwiki: 2018.04.22-0124
Theme: sprintdoc
refnotes: 2020-08-10

After installing plugin the whole wiki gets unreacheable and useless. I get the following error:

Fatal error: Class 'dokuwiki\Parsing\Parser' not found in /volume1/web/dokuwiki/lib/plugins/refnotes/bibtex.php on line 11 

Any advice?
Thanks!

**Comment by dwp-forge** [comment]
Duplicate of #54.

Update DW or use older plugin version.

**Comment by VadoLigure** [comment]
It works. Thank you very much and forgive the duplication.

Regards
