### ISSUE TITLE
No plugin section in configuration

### ISSUE THREAD

**Issue by ternite** [dwp-forge/refnotes#64]
Hi,

as far as I understand the [documentation,](https://www.dokuwiki.org/plugin:refnotes#configuration) there should be a plugin section within dokuwiki configuration.

Unfortunately, there is none in my installation.

I suspected an interference with another plugin, so I deactivated all of those I installed. This did not change the behavior.

DW version: Release 2020-07-29 "Hogfather"
Plugin version: 2020-08-10
Webserver: Apache/2.4.46 (Win32) PHP/7.4.12

What can I do to troubleshoot this problem?

Best regards
Thomas

**Comment by dwp-forge** [comment]
It shouldn't be within DW configuration page. There should be a separate link for RefNones on administration page.

![image](https://user-images.githubusercontent.com/11460562/108429718-08c15880-7249-11eb-8002-ff6e8cbeaf4d.png)

**Comment by ternite** [comment]
Thanks for your reply, and the screenshot!

Unfortunately, I also can't find such an entry:
![2021-02-19_00-40-57](https://user-images.githubusercontent.com/7860777/108436305-740c2a00-724b-11eb-8c34-62131dae18ee.png)

**Comment by dwp-forge** [comment]
Are there any signs of the issue in PHP log? You may need to enable [error logging](https://www.php.net/manual/en/errorfunc.configuration.php#ini.error-log) on your setup.

**Comment by ternite** [comment]
These are the messages logged there right after clicking into on the admin link (when the "Administration" page is loaded that I showed in my screenshot):

`[Fri Feb 19 10:43:24.663728 2021] [authz_core:error] [pid 18244:tid 856] [client 127.0.0.1:21584] AH01630: client denied by server configuration: D:/SynologyPraxis/Praxiswiki/dokuwiki/data/dont-panic-if-you-see-this-in-your-logs-it-means-your-directory-permissions-are-correct.png, referer: http://localhost:8800/doku.php?id=start&do=admin`

According to what I can read there, this should be an expected message. No further messages there.

These are the messages that are written during startup. (I am using the integrated, preconfigured server via run.cmd.)

`[Fri Feb 19 10:46:19.570115 2021] [core:warn] [pid 20044:tid 568] AH00098: pid file D:/SynologyPraxis/Praxiswiki/server/logs/httpd.pid overwritten -- Unclean shutdown of previous Apache run?
PHP Warning:  PHP Startup: Unable to load dynamic library 'pdo_sqlite' (tried: ./php/ext\\pdo_sqlite (Das angegebene Modul wurde nicht gefunden.), ./php/ext\\php_pdo_sqlite.dll (Das angegebene Modul wurde nicht gefunden.)) in Unknown on line 0`
`[Fri Feb 19 10:46:19.621100 2021] [mpm_winnt:notice] [pid 20044:tid 568] AH00455: Apache/2.4.46 (Win32) PHP/7.4.12 configured -- resuming normal operations`
`[Fri Feb 19 10:46:19.621100 2021] [mpm_winnt:notice] [pid 20044:tid 568] AH00456: Apache Lounge VS16 Server built: Oct  2 2020 10:45:47`
`[Fri Feb 19 10:46:19.621100 2021] [core:notice] [pid 20044:tid 568] AH00094: Command line: 'mapache.exe -d D:/{MYPATH}/dokuwiki/server'`
`[Fri Feb 19 10:46:19.625097 2021] [mpm_winnt:notice] [pid 20044:tid 568] AH00418: Parent: Created child process 12904`
`PHP Warning:  PHP Startup: Unable to load dynamic library 'pdo_sqlite' (tried: ./php/ext\\pdo_sqlite (Das angegebene Modul wurde nicht gefunden.), ./php/ext\\php_pdo_sqlite.dll (Das angegebene Modul wurde nicht gefunden.)) in Unknown on line 0`
`[Fri Feb 19 10:46:20.523542 2021] [mpm_winnt:notice] [pid 12904:tid 740] AH00354: Child: Starting 24 worker threads.`

The only thing I find worth noting is that "pdo_sqlite" is not loaded, but as far as I know, in my current installation there is no need for that.

**Comment by ternite** [comment]
> Does syntax part of the plugin work as expected?

I entered the example syntax `Here goes the reference[(This is a note.)].` into one of my pages, but the code is not parsed, apparently. No error message is logged there, either.

Since I'm new to the refnotes plugin, I don't know what to expect exactly, honestly. I read the documentation, but wanted to go straight into Structured References. As far as I understand it, configuration should be set right before being able to use that.

I'm aiming on including Literature Notes into my project and wanted several pages to make use of the same data source. I'm not sure if this is even possible with refnotes. I wanted to try and failed right at the beginning, when configuration was not available.

**Comment by dwp-forge** [comment]
Overall it appears that DW just doesn't see that plugin is there. Do you see it showing up in Extension Manager?

**Comment by ternite** [comment]
Stupid me. :(

While troubleshooting around with not finding a section on the configuration page, I must have **deactivated** the plugin at some point of time.

Of course, the configuration page is showing now, and it seems to be complete.

Thanks for your quick answers! I'd probably given up by now if not for your hint on where to find the configuration. 

Please note: as someone who did not know what to expect, but how plugin configuration usually is handled, my brain made me read the sentence `The RefNotes plugin has its own configuration interface that is available from the administration page.` as `The RefNotes plugin has its own configuration section that is available from the configuration page.`.

The current sentence is correct, of course, but can easily be misunderstood. Maybe you could rephrase this like: `The RefNotes plugin has a complex configuration that is not embedded into the dokuwiki configuration page. It has its own configuration interface which is made available by a separate link named "RefNotes Configuration" on the main administration page.`

And thanks, again!
