### ISSUE TITLE
Merging namespaces not possible with root namespace

### ISSUE THREAD

**Issue by quarterwave** [dwp-forge/refnotes#66]
On the [discussion page](https://www.dokuwiki.org/plugin:refnotes:discussion#consecutive_numbering), it is mentioned that one can use `~~REFNOTES : :refnotes:lit: ~~` from which I deduced that it is possible to merge the _root_ namespace with a sub namespace to create consecutive numbering.

But this is not possible. In my case, using `~~REFNOTES : abc def ~~` will merge the numbering of namespace `abc` and `def`, but references in the root namespace will be created as a _separate_ block with its _own numbering_.

**Comment by dwp-forge** [comment]
Fixed in f806d69.
