### ISSUE TITLE
Version 2021-05-10 changes render style from Harvard to basic, when using namespace merging

### ISSUE THREAD

**Issue by quarterwave** [dwp-forge/refnotes#67]
On DokuWiki "Hogfather" and refnotes 2021-05-10.

1. Given page content:

```
====== Playground ======

Lorem ipsum dolor sit amet, consectetuer adipiscing elit [(:book:smith>> page:1)]

[(:book:smith>>
author: Smith, Peter
year  : 1234
title : Lorem ipsum dolor sit amet
)]

~~REFNOTES :book: ~~
```

2. Settings for the namespace `:book:` set to:

- `reference-render`: Harvard system of referencing
- `note-render`: Harvard system of referencing

3. Then merging the root namespace with the `book` namespace by making the following modification:

`~~REFNOTES :book: ~~`
`~~REFNOTES : :book: ~~`

4. Will change the rendering style from Harvard style to basic style:

![image](https://user-images.githubusercontent.com/50782455/117777385-d66a3a80-b23c-11eb-95f2-0f1177230bfd.png)
![image](https://user-images.githubusercontent.com/50782455/117777633-15988b80-b23d-11eb-94b5-eff86539ea27.png)

**Comment by dwp-forge** [comment]
From [the documentation](https://www.dokuwiki.org/plugin:refnotes:syntax#namespace_merging):

> By default all notes and references from both namespaces will be rendered **using style of the first one**. You can override this behavior by explicitly inheriting specific style.

If you want to apply Harvard style tho the merged notes block you can either change the order:
```
~~REFNOTES :book: : ~~
```
or specify the style explicitly:
```
<refnotes : :book:> inherit: harvard </refnotes>
```
