### ISSUE TITLE
Adding and deleting namespace returns `TypeError`

### ISSUE THREAD

**Issue by quarterwave** [dwp-forge/refnotes#68]
Release 2020-07-29 "Hogfather" and refnotes installed version 2021-05-10. On the _RefNotes Configuration_ page, adding a new namespace results in the dialog error message:

`TypeError: can't convert undefined to object`

Deleting an existing namespace pops up a dialog with

`Are you sure you want to delete :table:stars: namespace?`

but clicking `Ok` and reloading the page shows that the namespace has not been deleted. Renaming an existing namespace still works.

**Comment by dwp-forge** [comment]
Fixed in [2021-05-23](https://github.com/dwp-forge/refnotes/releases/tag/v.2021-05-23).
