### ISSUE TITLE
Citation page number

### ISSUE THREAD

**Issue by Dob4115** [dwp-forge/refnotes#69]
I'm using the reference database and want to include page numbers in my citations. So I have a citation that looks like

> [(cite:LastName1991)]

And it renders inline as 
> [LastName1991]

with a larger description at the bottom of the wiki page. That's great. But I want to be able to include the specific page number within the citation so that it renders something like:
> [LastName1991, p.121]

I saw in the discussion archive, that this was added in the 2012-07-15 release, but I can't figure out the syntax for it. I read through the release notes for that version (on the main plugin page) but can't relate that to the present issue.

Thanks!

**Comment by dwp-forge** [comment]
You have to use Harvard reference rendering for `cite` namespace and add the page using [structured reference](https://www.dokuwiki.org/plugin:refnotes:structured#references) syntax:
```
[(cite:LastName1991>>page:121)]
```

**Comment by Dob4115** [comment]
Ok, so for note-render of the cite namespace I have "Harvard system of referencing", and I've got my citation string looking like what you show there. But this adds the page number to the end of the reference at the bottom of the page and, more importantly, makes the popup for every citation from the same source show one of the page numbers at the end. I guess I was expecting to see each citation's page number in the popup, not a "random" citation's page number.

Or am I missing something?

**Comment by dwp-forge** [comment]
You should set `reference-render` to Harvard. Or inherit all styling from default `harvard` namespace (if you didn't delete it):

```
<refnotes cite>
inherit: harvard
</refnotes>
```

**Comment by Dob4115** [comment]
Ok, got it. I wasn't using the reference-render setting. Thanks!
