### ISSUE TITLE
basic refnote has to end with a dot

### ISSUE THREAD

**Issue by bvdbos** [dwp-forge/refnotes#72]
I noticed a simple refnote has to end with a dot to become visible.

![afbeelding](https://user-images.githubusercontent.com/1064079/162127319-5a67f93c-b9b8-4f49-b912-4828c962940e.png)

Might be intended? But then would be good to include this in the documentation?

**Comment by dwp-forge** [comment]
It is not just about the period at the end. The text of the note "referentie1" is so basic that it is treated as a note name. See [named notes](https://www.dokuwiki.org/plugin:refnotes:syntax#named_notes):

> Alternative way of the note identification is giving it a unique name. For the name you can use any string of alpha-numeric characters and underscores that starts with a letter.
