### ISSUE TITLE
Ref-Author not working when coming after Author and Publisher not shown

### ISSUE THREAD

**Issue by eduardomozart** [dwp-forge/refnotes#73]
Hello,

I'm using the following BibTeX syntax:

````
<code bibtex>
@Comment{refnotes,
  namespace = "harvard"
}

@Article{TeamPass-ReadTheDocs-Upgrade,
  title      = "Upgrade",
  author     = "Nils {Laumaillé}"
  ref-author = "Laumaillé",
  publisher  = "TeamPass",
  url        = "https://teampass.readthedocs.io/en/latest/install/upgrade/",
  year       = 2017
}
</code>
````

With the following DokuWiki markdown:

````
Recomenda-se instalar a versão mais recente do TeamPass quando disponível. [(:harvard:TeamPass-ReadTheDocs-Upgrade)]
````

The following output is generated:

```
Recomenda-se instalar a versão mais recente do TeamPass quando disponível. (Nils Laumaillé, 2017)
```

It's not the expected output.

When inverting the ``ref-author`` and ``author`` fields, it's working as expected:

````
@Article{TeamPass-ReadTheDocs-Upgrade,
  title      = "Upgrade",
  ref-author = "Laumaillé",
  author     = "Nils {Laumaillé}"
  publisher  = "TeamPass",
  url        = "https://teampass.readthedocs.io/en/latest/install/upgrade/",
  year       = 2017
}
````

The following output is generated (as expected):

```
Recomenda-se instalar a versão mais recente do TeamPass quando disponível. (Laumaillé, 2017)
```

The second issue is that the ``publisher`` tag also isn't shown at the bottom of the page.

I'm using DokuWiki Release 2022-07-31a "Igor". Please let me know if anymore information are needed.

**Comment by dwp-forge** [comment]
There is a comma missing after `author = "Nils {Laumaillé}"`, so the following field is skipped by the parser. In the "working" case `publisher` is missing in the note text.
