### ISSUE TITLE
Enhancement

### ISSUE THREAD

**Issue by sugenganthos** [dwp-forge/refnotes#74]
Based on [harvard quick guide](https://library.aru.ac.uk/referencing/harvard.htm), I've made some changes:
- e-publication type for electronic publication
- _accessed on_ for electronic publication view time
- 4 or more author will be displayed as first author + *et al*. Except for custom ref-author display.
Here the changed file (php but renamed as txt)

Thankyou

[rendering.txt](https://github.com/dwp-forge/refnotes/files/9957847/rendering.txt)

**Comment by dwp-forge** [comment]
Implemented in 68735bb (I decided to use `format` instead of `epub-type`), a809558 and b13d1b4.
