### ISSUE TITLE
Structured references and `~~REFNOTES~~'

### ISSUE THREAD

**Issue by nerun** [dwp-forge/refnotes#76]
When i use structured references, the note do not appear under `~~REFNOTES~~`. Example:

Under namespace `refnotes` i have a page with a sheet with many notes like this one:

:ref:USC-17-1-102 | UNITED STATES. [United States Code, Title 17, Chapter 1, §102](https://uscode.house.gov/view.xhtml?req=granuleid:USC-prelim-title17-section102&num=0&edition=prelim). Subject matter of copyright: in general.
-- | --

I call it: `[(:ref:USC-17-1-102)]`, but it is rendered allways at BOTTOM of page, NOT UNDER `~~REFNOTES~~`.

**Comment by dwp-forge** [comment]
Try [this](https://www.dokuwiki.org/plugin:refnotes:syntax#note_blocks):
```
~~REFNOTES ref ~~
```

**Comment by nerun** [comment]
It works! BUT... Other notes that are not structured references, don't render below `~~REFNOTES ref~~`.

For example:
```
"Lorem ipsum" text here. [(:ref:USC-17-1-102)] [(Not structured note here.)]

==== REFERENCES ====
~~REFNOTES ref ~~

Other paragraph here.

```
Is rendered:

```
"Lorem ipsum" text here. [1] [1]

REFERENCES
1. UNITED STATES. United States Code, Title 17, Chapter 1, §102. Subject matter of copyright: in general.

Other paragraph here.

------------------------------------------------------------------
1. Not structured note here.
```

**Comment by dwp-forge** [comment]
How about [this](https://www.dokuwiki.org/plugin:refnotes:syntax#namespace_merging):
```
~~ REFNOTES ref : ~~
```

Hint: You may want to read the rest of the [linked page](https://www.dokuwiki.org/plugin:refnotes:syntax) as well :wink:

**Comment by nerun** [comment]
Perfect!
