### ISSUE TITLE
ptln() is deprecated

### ISSUE THREAD

**Issue by prolibre** [dwp-forge/refnotes#80]
Hello,

In Dokuwiki stable version (Release 2024-02-06 "Kaos")

I have : 

`ptln() is deprecated. It was called from refnotes_html_sink::ptln() in /DIR/wiki/lib/plugins/refnotes/admin.php:744 echo should be used instead!`

in deprecated error log.

Thanks and have a nice day !

**Comment by dwp-forge** [comment]
Fixed in [v.2024-02-12](https://github.com/dwp-forge/refnotes/releases/tag/v.2024-02-12).
