### ISSUE TITLE
Is it possible to stop refnotes from being made on a page?

### ISSUE THREAD

**Issue by ProjectsKoryHasWorkedOn** [dwp-forge/refnotes#81]
Facing a scenario where when using LaTeX, I might have nested parentheses like (()) or [[]] but don't want references on that page 
Aside from wrapping brackets with `<wrap></wrap>` or adding `left(,` and `\right)`  for every bracket to stop double parentheses in LaTeX is there a proper way to stop these math pages from having references
Perhaps specifying the syntax used for refnotes like `<refnote></refnote>` would be preferable 

Guess in theory, I could try changing 

`$entry = '<refnote>'` and `$exit = '</refnote>'` in syntax php files but it's a little hard to work out which variables to change

**Comment by dwp-forge** [comment]
I'm not sure about LaTeX syntax specifics, but wouldn't it be agnostic to spaces (i.e. `[ ( expression ) ]`)? 

If you want to play with the syntax yourself, you could start at [syntax/references.php:45](https://github.com/dwp-forge/refnotes/blob/master/syntax/references.php#L45).

**Comment by ProjectsKoryHasWorkedOn** [comment]
Oh, I didn't even think of that. Yeah spaces is a simple fix


No refnotes
```
<math>[ ( expression ) ]</math> 
<math>( ( expression ) )</math> 
<math>( (expression))</math> 
```

Refnotes
`<math>[(expression)]</math> `
